/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarraNavegacao: typeof import('./components/barra-navegacao.vue')['default']
    CardExercicio: typeof import('./components/card-exercicio.vue')['default']
    CardTreino: typeof import('./components/card-treino.vue')['default']
    Header: typeof import('./components/header.vue')['default']
    HeaderPaginas: typeof import('./components/header-paginas.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
