/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarraNavegacao: typeof import('./components/BarraNavegacao.vue')['default']
    CardTreino: typeof import('./components/CardTreino.vue')['default']
    HeaderPaginas: typeof import('./components/HeaderPaginas.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Timer: typeof import('./components/Timer.vue')['default']
  }
}
