/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/CriarTreino': RouteRecordInfo<'/CriarTreino', '/CriarTreino', Record<never, never>, Record<never, never>>,
    '/EditarTreino/[id]': RouteRecordInfo<'/EditarTreino/[id]', '/EditarTreino/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/Historico': RouteRecordInfo<'/Historico', '/Historico', Record<never, never>, Record<never, never>>,
    '/Inicio': RouteRecordInfo<'/Inicio', '/Inicio', Record<never, never>, Record<never, never>>,
    '/Treino/[id]': RouteRecordInfo<'/Treino/[id]', '/Treino/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/Treinos': RouteRecordInfo<'/Treinos', '/Treinos', Record<never, never>, Record<never, never>>,
  }
}
